services:

  mongodb:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    image: task-manager-mern-backend:latest 
    container_name: task-backend

    ports:
      - "5000:5000"

    environment:
      NODE_ENV: PRODUCTION
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/taskdb

    depends_on:
      - mongodb

    restart: always
    networks:
      - app-network

  frontend:
    image: task-manager-mern-frontend:latest 
    container_name: task-frontend

    ports:
      - "3000:3000"

    environment:
      REACT_APP_API_URL: http://backend:5000

    depends_on:
      - backend

    restart: always
    networks:
      - app-network


  postgres:
    image: postgres:15
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge