services:

  mongodb:
    image: mongo:6
    container_name: mongo

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - mongo_data:/data/db

    restart: always

    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "password", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - app-network



  backend:
    build:
      context: ./backend

    container_name: task-backend

    ports:
      - "5000:5000"

    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017/taskdb?authSource=admin
      NODE_ENV: development
      PORT: 5000

    depends_on:
      mongodb:
        condition: service_healthy

    restart: always

    networks:
      - app-network



  frontend:
    build:
      context: ./frontend

    container_name: task-frontend

    ports:
      - "3000:3000"

    environment:
      REACT_APP_API_URL: http://localhost:5000

    depends_on:
      - backend

    restart: always

    networks:
      - app-network



  postgres:
    image: postgres:15
    container_name: sonarqube-db

    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - app-network



  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube

    ports:
      - "9000:9000"

    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

    restart: always

    networks:
      - app-network



volumes:
  mongo_data:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:



networks:
  app-network: