version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "password", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: ./backend
    container_name: task-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017/taskdb?authSource=admin
      NODE_ENV: development
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: task-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data: